USE [master]
GO
/****** Object:  Database [snakegame]    Script Date: 16-6-2022 13:32:39 ******/
CREATE DATABASE [snakegame]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'snakegame', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\snakegame.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'snakegame_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\snakegame_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [snakegame] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [snakegame].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [snakegame] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [snakegame] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [snakegame] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [snakegame] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [snakegame] SET ARITHABORT OFF 
GO
ALTER DATABASE [snakegame] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [snakegame] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [snakegame] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [snakegame] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [snakegame] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [snakegame] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [snakegame] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [snakegame] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [snakegame] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [snakegame] SET  DISABLE_BROKER 
GO
ALTER DATABASE [snakegame] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [snakegame] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [snakegame] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [snakegame] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [snakegame] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [snakegame] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [snakegame] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [snakegame] SET RECOVERY FULL 
GO
ALTER DATABASE [snakegame] SET  MULTI_USER 
GO
ALTER DATABASE [snakegame] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [snakegame] SET DB_CHAINING OFF 
GO
ALTER DATABASE [snakegame] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [snakegame] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [snakegame] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [snakegame] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'snakegame', N'ON'
GO
ALTER DATABASE [snakegame] SET QUERY_STORE = OFF
GO
USE [snakegame]
GO
/****** Object:  Table [dbo].[mulitple_answers]    Script Date: 16-6-2022 13:32:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[mulitple_answers](
	[id] [int] NOT NULL,
	[multiple_answers] [varchar](255) NULL,
 CONSTRAINT [PK_mulitple_answers] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[questions]    Script Date: 16-6-2022 13:32:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[questions](
	[id] [int] NOT NULL,
	[questions] [varchar](255) NULL,
	[answers] [varchar](255) NULL,
 CONSTRAINT [PK_questions] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [snakegame] SET  READ_WRITE 
GO